<?php

namespace Plugin\EccubeApi\Repository\OAuth2\OpenID;

use Doctrine\ORM\EntityRepository;

/**
 * UserInfoAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInfoAddressRepository extends EntityRepository
{
}
