<?php

namespace Plugin\EccubeApi\Repository\OAuth2;

use Doctrine\ORM\EntityRepository;
use Plugin\EccubeApi\Entity\OAuth2\AccessToken;
use OAuth2\Storage\AccessTokenInterface;


/**
 * AccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Kentaro Ohkouchi
 * @link http://bshaffer.github.io/oauth2-server-php-docs/cookbook/doctrine2/
 */
class AccessTokenRepository extends EntityRepository implements AccessTokenInterface
{
    /**
     * トークンを指定して、 access token のフィールドの配列を返す.
     *
     * @param string $oauthToken トークン文字列
     * @return array access token のフィールドの配列
     */
    public function getAccessToken($oauthToken)
    {
        $AccessToken = $this->findOneBy(array('token' => $oauthToken));
        if (is_object($AccessToken)) {
            $token = $AccessToken->toArray();
            $Client = $AccessToken->getClient();
            if ($Client->hasMember() || $Client->hasCustomer()) {
                $token['client_id'] = $Client->getId();
                $UserInfo = $AccessToken->getUser();
                if ($UserInfo) {
                    $token['user_id'] = $UserInfo->getSub();
                }
                $token['expires'] = $token['expires']->getTimestamp();
                return $token;
            }
        }
        return null;
    }

    /**
     * AccessToken を生成して保存する.
     *
     * @param string $oauthToken トークン文字列
     * @param string $clientIdentifier client_id 文字列
     * @param integer $user_id UserInfo::id
     * @param integer $expires 有効期限の UNIX タイムスタンプ
     * @param string $scope 認可された scope. スペース区切りで複数指定可能
     * @return void
     */
    public function setAccessToken($oauthToken, $clientIdentifier, $user_id, $expires, $scope = null)
    {
        $client = $this->_em->getRepository('Plugin\EccubeApi\Entity\OAuth2\Client')
                            ->findOneBy(array('client_identifier' => $clientIdentifier));
        // response_type=token の時は UserInfo::id が渡ってくる. それ以外は UserInfo::sub が渡ってくる
        $searchConditions = array();
        if (is_numeric($user_id)) {
            $searchConditions['id'] = $user_id;
        } else {
            $searchConditions['sub'] = $user_id;
        }
        $user = $this->_em->getRepository('Plugin\EccubeApi\Entity\OAuth2\OpenID\UserInfo')->findOneBy($searchConditions);
        $AccessToken = new \Plugin\EccubeApi\Entity\OAuth2\AccessToken();
        $now = new \DateTime();
        $AccessToken->setPropertiesFromArray(array(
            'token'     => $oauthToken,
            'client'    => $client,
            'user'      => $user,
            'expires'   => $now->setTimestamp($expires),
            'scope'     => $scope,
        ));
        $this->_em->persist($AccessToken);
        $this->_em->flush($AccessToken);
    }
}
