<?php

/*
 * This file is part of the EccubeApi
 *
 * Copyright (C) 2016 LOCKON CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\EccubeApi\Repository\OAuth2;

use Doctrine\ORM\EntityRepository;
use Plugin\EccubeApi\Entity\OAuth2\RefreshToken;
use OAuth2\Storage\RefreshTokenInterface;

/**
 * RefreshTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Kentaro Ohkouchi
 * @link http://bshaffer.github.io/oauth2-server-php-docs/cookbook/doctrine2/
 */
class RefreshTokenRepository extends EntityRepository implements RefreshTokenInterface
{
    /**
     * トークンを指定して RefreshToken のフィールドの配列を取得する.
     *
     * @param string $token トークン文字列
     * @return array RefreshToken のフィールドの配列
     */
    public function getRefreshToken($token)
    {
        $refreshToken = $this->findOneBy(array('refresh_token' => $token));
        if ($refreshToken) {
            $Client = $refreshToken->getClient();
            $User = $refreshToken->getUser();
            $refreshToken = $refreshToken->toArray();
            $refreshToken['expires'] = $refreshToken['expires']->getTimestamp();
            if ($Client) {
                $refreshToken['client_id'] = $Client->getClientIdentifier();
            } else {
                $refreshToken['client_id'] = null;
            }
            if ($User) {
                $refreshToken['user_id'] = $User->getSub();
            } else {
                $refreshToken['user_id'] = null;
            }
        }
        return $refreshToken;
    }

    /**
     * トークンを指定して RefreshToken を生成して保存します.
     *
     * @param string $refreshToken トークン文字列
     * @param string $clientIdentifier client_id 文字列
     * @param integer $user_id UserInfo::id
     * @param integer $expires 有効期限の UNIX タイムスタンプ
     * @param string $scope 認可された scope. スペース区切りで複数指定可能
     * @return void
     */
    public function setRefreshToken($refreshToken, $clientIdentifier, $user_id, $expires, $scope = null)
    {
        $client = $this->_em->getRepository('Plugin\EccubeApi\Entity\OAuth2\Client')
            ->findOneBy(
                array('client_identifier' => $clientIdentifier)
            );
        // response_type=token の時は UserInfo::id が渡ってくる. それ以外は UserInfo::sub が渡ってくる
        $searchConditions = array();
        if (is_numeric($user_id)) {
            $searchConditions['id'] = $user_id;
        } else {
            $searchConditions['sub'] = $user_id;
        }
        $user = $this->_em->getRepository('Plugin\EccubeApi\Entity\OAuth2\OpenID\UserInfo')->findOneBy($searchConditions);
        $RefreshToken = new \Plugin\EccubeApi\Entity\OAuth2\RefreshToken();
        $now = new \DateTime();
        $RefreshToken->setPropertiesFromArray(array(
           'refresh_token'  => $refreshToken,
           'client'         => $client,
           'user'           => $user,
           'expires'        => $now->setTimestamp($expires),
           'scope'          => $scope,
        ));
        $this->_em->persist($RefreshToken);
        $this->_em->flush($RefreshToken);
    }

    /**
     * RefreshToken を削除します.
     *
     * @param string $refreshToken トークン文字列
     * @return void
     */
    public function unsetRefreshToken($refreshToken)
    {
        $refreshToken = $this->findOneBy(array('refresh_token' => $refreshToken));
        if ($refreshToken) {
            $this->_em->remove($refreshToken);
            $this->_em->flush($refreshToken);
        }
    }
}
