<?php

/*
 * This file is part of the EccubeApi
 *
 * Copyright (C) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */


namespace Plugin\EccubeApi\Repository\OAuth2;

use Eccube\Entity\Member;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\EntityRepository;
use OAuth2\Storage\ScopeInterface;
use OAuth2\RequestInterface;

/**
 * ScopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Kentaro Ohkouchi
 * @link http://bshaffer.github.io/oauth2-server-php-docs/cookbook/doctrine2/
 */
class ScopeRepository extends EntityRepository implements ScopeInterface
{
    /**
     * {@inheritdoc}
     */
    public function scopeExists($scope)
    {
        $scopes = explode(' ', $scope);
        $qb = $this->createQueryBuilder('s');
        $qb->select('COUNT(s.id)')
            ->where($qb->expr()->in('s.scope', $scopes));
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count == count($scopes);
    }

    /**
     * {@inheritdoc}
     */
    public function getDefaultScope($client_id = null)
    {
        $Scopes = $this->findBy(array('is_default' => true));
        if ($Scopes) {
            $defaultScopes = array_map(
                function ($Scope) {
                    return $Scope->getScope();
                }, $Scopes
            );
            return implode(' ', $defaultScopes);
        }
        return null;
    }

    /**
     * スペース区切りの scope の文字列とユーザーが使用可能なスコープを返します.
     *
     * @param string $scope スーペース区切りの scope の文字列
     * @param UserInterface 対象のユーザー
     * @return array Scope の配列
     */
    public function findByString($scope, UserInterface $User)
    {
        if ($User instanceof Member) {
            $search_key = 'member_flg';
        } else {
            $search_key = 'customer_flg';
        }
        $scopes = explode(' ', $scope);
        $qb = $this->createQueryBuilder('s');
        $qb->select('s')
            ->where($qb->expr()->in('s.scope', $scopes))
            ->andWhere('s.'.$search_key.' = 1');
        return $qb->getQuery()->getResult();
    }
}
