<?php

namespace Plugin\EccubeApi\Repository\OAuth2;

use Doctrine\ORM\EntityRepository;
use OAuth2\Storage\UserCredentialsInterface;
use OAuth2\OpenID\Storage\UserClaimsInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @link http://bshaffer.github.io/oauth2-server-php-docs/cookbook/doctrine2/
 */
class UserRepository extends EntityRepository implements UserCredentialsInterface, UserClaimsInterface
{
    public function checkUserCredentials($email, $password)
    {
        $user = $this->findOneBy(array('email' => $email));
        if ($user) {
            return $user->verifyPassword($password);
        }
        return false;
    }

    /**
     * @return
     * ARRAY the associated "user_id" and optional "scope" values
     * This function MUST return FALSE if the requested user does not exist or is
     * invalid. "scope" is a space-separated list of restricted scopes.
     * @code
     * return array(
     *     "user_id"  => USER_ID,    // REQUIRED user_id to be stored with the authorization code or access token
     *     "scope"    => SCOPE       // OPTIONAL space-separated list of restricted scopes
     * );
     * @endcode
     */
    public function getUserDetails($email)
    {
        $user = $this->findOneBy(array('email' => $email));
        if ($user) {
            $user = $user->toArray();
        }
        return $user;
    }
    // TODO implements user claims
    public function getUserClaims($user_id, $scope) {
        return array('sub' => 'aaa'); // FIXME
    }
}
